services:
  - type: web
    name: mediconnect
    runtime: node
    plan: free
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://thomasshelby09766_db_user:GRUfeMpYV50XIFr9@cluster0.pbmt6oy.mongodb.net/mediconnect_pro?appName=Cluster0
      - key: JWT_SECRET
        value: mediconnect_super_secret_key_2024_production
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://mediconnect.onrender.com
      - key: PORT
        value: 5000
